<?php
//
// File generated by Dolibarr installer 22.0.3 on 08 Fév. 2026
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//


// Très important pour Traefik et les URLs de tes clients
$dolibarr_main_url_root = 'http://' . getenv('CLIENT_HOSTNAME');
//$dolibarr_main_url_root='http://client1.localhost';

$dolibarr_main_document_root="/var/www/html";
$dolibarr_main_url_root_alt='/custom';
$dolibarr_main_document_root_alt="/var/www/html/custom";
$dolibarr_main_data_root="/var/www/documents";
//$dolibarr_main_db_host='db-c1';
$dolibarr_main_db_host = getenv('DB_HOST') ?: 'db';
$dolibarr_main_db_port='5432';
//$dolibarr_main_db_name='dolibarr';
$dolibarr_main_db_name = getenv('DB_NAME') ?: 'dolibarr';
$dolibarr_main_db_prefix='llx_';
//$dolibarr_main_db_user='dolibarr';
$dolibarr_main_db_user = getenv('DB_USER');
//$dolibarr_main_db_pass='pass_c1';
$dolibarr_main_db_pass = getenv('DB_PASS');
$dolibarr_main_db_type='pgsql';
$dolibarr_main_db_character_set='UTF8';
$dolibarr_main_db_collation='';

// Authentication settings
$dolibarr_main_authentication='dolibarr';

//$dolibarr_main_demo='autologin,autopass';
// Security settings
$dolibarr_main_prod='0';
$dolibarr_main_force_https='0';
$dolibarr_main_restrict_os_commands='mariadb-dump, mariadb, mysqldump, mysql, pg_dump, pg_restore, clamdscan, clamdscan.exe';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_instance_unique_id='3ed3e5d28662a63b436b215fba319f8a';
$dolibarr_mailing_limit_sendbyweb='0';
$dolibarr_mailing_limit_sendbycli='0';

//$dolibarr_lib_FPDF_PATH="";
//$dolibarr_lib_TCPDF_PATH="";
//$dolibarr_lib_FPDI_PATH="";
//$dolibarr_lib_TCPDI_PATH="";
//$dolibarr_lib_GEOIP_PATH="";
//$dolibarr_lib_NUSOAP_PATH="";
//$dolibarr_lib_ODTPHP_PATH="";
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP="";
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';

//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
$dolibarr_main_distrib='standard';
